= OpenMinTeD Interoperability Scenarios
:Author: TBD
:toc-title: Contents

This document will host the interoperability scenarios for the OpenMinTeD platform generated as part of working package (WP) 5 deliverables.

= Introduction

The task was aimed to produce interoperability scenarios relevant to each working group (WG).

== Scenario definition

a concrete interoperability scenario is defined and their issues should be made explicit. These scenarios should be based on practical experience or obvious constellations motivated through the constellation of the WG participants. This happens mainly during and shortly after the F2F workshops. It is expected that more scenarios will be generated than can be work upon within the first year in which the regular F2F meetings take place. Additionally, it is expected that scenarios and interoperability specifications they generate will require refinement. These extra scenarios and refinement should drive the work of the working groups throughout the remainder of the project.

=== Questions to consider

* What is the scenario?
* Why is the scenario relevant to the WG?
* Why is the scenario relevant to the other WGs?
* Why is the scenario relevant to external experts?
* How could OpenMinTeD / the WGs address it?
* What kind of feedback could we expect from other WGs / external experts for that scenario?

= Interoperability scenarios

include::{include-dir}WG1.adoc[]

<<<

include::{include-dir}WG2.adoc[]

<<<

include::{include-dir}wg3.adoc[]

<<<

//include::{include-dir}wg4.adoc[]

//TODO: add highlighted text to all scenario items
//TODO: add figures to WG2 scenarios
//TODO: add additional missing subsections (cf. WG1 google doc)