= OpenMinTeD Interoperability Specification
:Author: OpenMinTeD Interoperability Team (T5.2)
:toc-title: Contents

This document will host the interoperability specification for the OpenMinTeD platform. Currently,
there is not much to see here. For the time being, we use this place to dump intermediate
information that may or may not end up in the final specification.

= Introduction

== Requirement metadata

=== ID

Every requirement has an ID. We start counting from 1 and every new requirement increments the
ID by 1. The ID is encoded in the requirement filename, e.g. `1.adoc`.

=== Concreteness

The OpenMinTeD platform aims to be open and inclusive. As such, it aims to support multiple popular
technologies and standards. As popularity is changing over time and as new standards and
technologies are evolving, the platform will have to evolve as well. The distinction between
abstract and concrete interoperability requirements that we make here allows us to answer two questions:

* How difficult is it for a new technology or standard to be incorporated into the platform?
* How difficult is it to integrate new components based on already supported technologies and standards
  into the platform.

Abstract requirements are agnostic to concrete technologies and standards and help assessing 
compliance with them; helps answering the first question. Concrete requirements refer to specific
implementation details and help answering the second question.

.Requirement concreteness values
* *Abstract* - the requirement specifies a need, but does not go into details how this
  need must be fulfilled. The requirement may provide examples of techniques or implementations that
  fulfill the requirement, but does not mandate their use.
* *Concrete* - the requirement specifies a need and prescribes the use of specific techniques,
  standards, implementations, etc..

=== Strength

.Requirement strength values
* *Mandatory* - compliance with a mandatory requirement is obligatory. Non-compliance with any 
  mandatory requirement entails non-compliance with the specification as a whole. 
* *Recommended* - compliance with a recommended requirement is not obligatory but strongly desired.
* *Optional* - compliance with an optional requirement is not obligatory and not strongly desired,
  but considered beneficial.

=== Status

The requirement status indicates how far it has proceeded in its lifecycle. If and which changes may
be made to a requirement depends on this status.

.Requirement status values
* *Draft* - the requirement is a suggestion and can be changed substantially in any respect.
* *Final* - the requirement is ready for release. Changes to a final requirement are only allowed
            if they do not affect the compliance status of any product, component, format, etc. that
            as already been evaluated against the requirement specification. If a change would
            trigger a change in any compliance status, instead of changing an existing requirement,
            a new requirement must be created under a new ID and compliance must be evaluated against
            this new requirement specification in the next iteration. The previous requirement must
            be moved to deprecated status.
* *Deprecated* - the requirement is no longer to be used for compliance assessment. The requirement
            specification must not be changed. An exception are amendments adding pointers to
            potential new versions of the requirement and providing a rationale for the deprecation.
            
=== Category

The category of a requirement is used to anchor it in the document structure of the interoperability
specification. The actual document structure is kept in a separate file to faciliate its refactoring.
A requirement may be in multiple categories which must be provided as a comma-separated list.

== Compliance assessment

=== Requirement compliance levels

* *Full* - fully compliant
* *Partial* - partially compliant. E.g. some parts of a product are compliant but not all. This is
  typically the case if a product is in a state of transition from a non-compilant to a compliant
  state.
* *No* - not compliant.
* *N/A* - not applicable. This is expected to occur mainly for concrete requirements if a certain
  requirement is not applicable for a certain implementation, e.g. a requirement on remote API
  access on a tool which does not offer a remote API. Abstract requirements should be formulated 
  in such a way that they are always applicable.

=== Overall compliance levels

* *None* - not compliant at all
* *Silver* - fully compliant with all mandatory requirements
* *Gold* - fully compliant with all mandatory and recommended requirements
* *Platin* - fully compliant with all mandatory, recommended, and optional requirements

Overall compliance levels are maintained separately for abstract and concrete requirements. A
product may attain a higher compliance level on abstract requirements than on concrete requirements.
For example, an abstract mandatory requirement may be to provide metadata in a machine-readable format while
a related concrete requirement may prescribe a certain metadata format. If a product offers
metadata in a machine-readable format, it would be fully compliant with the abstract requirement,
but if it does not use the metadata format prescribed by the concrete requirement, it is not compliant
here. The product may thus attain *silver* compliance on the abstract level, but *no* overall
compliance level on the concrete level.

=== Compliance profile

A compliance profile is a machine readable file that describes the compliance of a product,
component, format, etc. with the interoperability requirements.

NOTE: The format and schema of this file is still to be determined. YAML may be a good format
      candidate. 

== Adding new requirements

=== Files and IDs

Requirements are maintained in the folder `req`, one requirement per file, and files are numbered
starting at 1. The number corresponds to the ID of the requirement.

NOTE: Presently, the ID is not present inside the requirements file nor is it visible in the this
      document. We will add an post-processing step to automatically add the ID to the rendered
      document. See also link:https://github.com/openminted/interoperability-spec/issues/2[this issue].

NOTE: Presently, links to new requirements have to be added manually to the `WG1.adoc` - `WG4.adoc`
      files. This will also be automatically done soon. See also link:https://github.com/openminted/interoperability-spec/issues/3[this issue].

=== Template

This is the template we presently use for recording the requirements. It contains the requirement
metadata as described above and a description. Links to other requirements can be embedded in the
description.

[source,asciidoc]
----
include::{include-dir-spec}req/TEMPLATE.adoc[]
----

And this is how the requirement is rendered in this document (except the heading which doesn't work
in this particular example).

====
include::{include-dir-spec}req/TEMPLATE.adoc[]
====

=== Add a Requirement
Click on btn:[Create] to create a new requirement
 
= Requirements

include::{include-dir-spec}WG1.adoc[]
include::{include-dir-spec}WG2.adoc[]
include::{include-dir-spec}WG3.adoc[]
include::{include-dir-spec}WG4.adoc[]

include::{include-dir-spec}Details.adoc[]
include::{include-dir-spec}bibliography.adoc[]
