== Analytics components

NOTE: This is an example section to illustrate requirements specification and compliance assessment.

=== Components should be described by machine-readable metadata

[%hardbreaks]
[small]#*_Concreteness:_* __abstract__#
[small]#*_Strength:_* __mandatory__#

In order to incorporate components into the platform in an efficient manner, the platform must be
able to automatically obtain information about them. Hence, components must provide machine-readable
metadata by which they describe themselves. 

[cols="2,1,4"]
|====
|Product|Compliant|Justification

| Alvis
| full
| Alvis component descriptors

| ARGO/U-Compare
| full
| UIMA Analysis Engine descriptors

| DKPro Core
| full
| UIMA Analysis Engine descriptors

| GATE
| full
| CREOLE descriptors

| ILSP
| full
| UIMA Analysis Engine descriptors
|====


=== Component metadata should be embedded into the component source code

[%hardbreaks]
[small]#*_Concreteness:_* __abstract__#
[small]#*_Strength:_* __recommended__#

To avoid implementation and metadata getting out-of-sync, the metadata should be closely integrated
with the component source code such that e.g. parameter names and types are obtained directly from
the implementation (cf. <<uimafit>>).

[cols="2,1,4"]
|====
|Product|Compliant|Justification

| Alvis
| not
| Alvis XML descriptors manually maintained

| ARGO/U-Compare
| not (I believe)
| UIMA XML descriptors manually maintained

| DKPro Core
| full
| using uimaFIT Java annotations to automatically generate UIMA XML descriptors

| GATE
| partial
| using CREOLE Java annotations, but not yet in all components

| ILSP
| unknown
| unknown
|====


=== Component metadata is separable from the component

[%hardbreaks]
[small]#*_Concreteness:_* __abstract__#
[small]#*_Strength:_* __mandatory__#

The component metadata should be provided in such a way that it is separable from the component.
I.e. despite the canonical source of much of the metadata being the source code (and in a second
instance, the compiled code), it should not be necessary to inspect the source code (or compiled
code) to access the metadata or to actually invoke the component. Instead, the component should be
accompanied by a metadata file that was automatically generated during build time. Component
repositories for example should use this file when looking for component metadata. The file should
be at a well-known location within the component artifact.

[cols="2,1,4"]
|====
|Product|Compliant|Justification

| Alvis
| full or partial
| Alvis XML exist separately from the code - FIXME: unknown how Alvis components are packaged and if
the metadata file is in a well-known location.

| ARGO/U-Compare
| partial
| UIMA XML descriptors manually maintained

| DKPro Core
| full
| using uimaFIT to automatically generate UIMA XML descriptors. XML descriptors as always next to
the respective component classes. Pointers to all XML descriptors as stored in at
`META-INF/org.apache.uima.fit/components.txt` within the respective JAR files.

| GATE
| partial
| only for those components that still use CREOLE descriptors and do *not* use CREOLE Java annotations

| ILSP
| unknown
| unknown
|====
