== Adding version information in the metadata descriptions of all resources

[%hardbreaks]
[small]#*_Concreteness:_* __concrete__#
[small]#*_Strength:_*     __mandatory__#
[small]#*_Category:_*     __WG1__,__WG2__,__WG3__,__WG4__#
[small]#*_Status:_*       __draft__#

.See also

* <<REQ-32>>
* <<REQ-96>>

Although versioning is considered important for all resource types, the practices used for its encoding differ across them. 
Therefore, in OpenMinTeD the general rule is that the version of the resource must be clearly indicated in its metadata description. This is done with the element 'version' (of type _xs:string_) and, if the providers wish, they can also provide more information about the types of changes between the versions in the element 'revision' and the date of the last update ('lastDateUpdated'). 

However, the values that the 'version' element takes can differ depending on the source and resource type; given that the OMTD-SHARE element 'version' is of type _xs:string_, this can be accommodated without problems in the mapping process:

* For publications: following the OpenAIRE guidelines (new version to be released), the values of the OpenAIRE element 'version' must be taken from a controlled vocabulary (_accepted, published, draft, submitted, updated_)

* For all other resources, the most popular practice is to provide a number (e.g. 1.0, 3.0.1 etc.) and this is endorsed by OpenMinTeD; link:http://semver.org[semantic versioning] principles are recommended where possible for its assignment; the element, though, where this information is encoded in existing metadata descriptions may differ: 

- For components collected from Maven repositories: according to <<REQ-96>>, this information must be added in the 'version' element in the pom xml file

- For resources described with metadata in RDF, the 'owl:versionInfo' is the equivalent to the OMTD-SHARE 'version' element

- If there is no information on the metadata record of a resource harvested into OMTD, the version element is to be filled in with the creation date of the resource and, if this is again missing, the date of the registration of the resource in OpenMinTeD.

NOTE: In the next version of the schema, the "version" element will be restricted to the numeric type of encoding versions, following the http://semver.org[semantic versioning] principles, and another element will be added that will be of type "controlled vocabulary" that will take values such as _accepted, published, submitted_ etc. for publications, but also _alpha, beta, testing_ etc. for s/w resources.


.Compliance assessment
[cols="2,1,1,4,1"]
|====
|Product|Version|Compliant|Justification|Status

| CORE
|
| Partial
| Versions exist for the components
| Draft

| OpenAIRE
|
| Unknown
| Unknown
| Draft

| Frontiers
|
| No
| Available Q3 2017
| Final


| Alvis
| 0.5rc
| Partial
| Versions exist for the components. In general, version for resources has to be adapted to follow the link:http://semver.org[semantic versioning] principles.
| Draft

| ARGO
| 0.5
| Partial
| Type Systems and Components have versioning information, however other resources do not.
| Draft

| DKPro Core
| 1.8.0
| Full
| Version information is contained in the pom file
| Draft

| GATE
| 9
| Full
| Components distributed via maven include version information within the pom.xml file.
| Draft

| ILSP
| 1.2.1
| No
| Not supported yet
| Draft

| TheSoz
| June-16
| Full
| `owl:versionInfo` in `void.ttl` file
| Final

| Agrovoc
| 21/01/2016
| Partial
| modification date (dcterms:modified) is available
| Final

| OLiA
| June-16
| Partial
| no version id, but a textual description of the resource’s evolution.
| Final

| LAPPS
| June-16
| No
| 
| Final
|====
