=== Components that use external knowledge resources should delegate access to a resource adapter instead of handling it themselves

[%hardbreaks]
[small]#*_Concreteness:_* __abstract__#
[small]#*_Strength:_*     __optional__#
[small]#*_Category:_*     __WG2__,__WG4__#
[small]#*_Status:_*       __draft__#

A component that uses an external knowledge resources, e.g. a dictionary, should access that resource through an adapter instead of accessing it directly. E.g. a Gazeteer component could be configured with a WordListFileResourceAdapter that looks up words from a simple word list file or using some SparqlQueryAdapter that would perform the lookup via Sparql. Thus, providing access to different knowledge sources should not require changes to the component implementation itself, but rather require only the implementation of lightweight adapters. It is not important that all implementations use the same adapters, but rather that this abstraction exists in the first place. E.g. a GATE component may use a GATE-specific adapter implementation and a UIMA component may use an UIMA-specific implementation.

Note: UIMA External Resources could be used for this and I am pretty sure GATE also has one or more abstraction for such things.

Source: WG 2 Scenario 3 — The relation between documents and knowledge bases through keywords

Required actions: While UIMA has the general abstraction, there are no common implementations for different types of knowledge resources. I think GATE has some typical/common abstractions like a gazetter and probably others. These should be inspected and additional recommendations for specific resource types may be given in future requirements. Mind that even if GATE/UIMA have such abstractions, it does not mean that they are consistently used or used at all. This should be brought to the attention of the component collection providers.

Note: This requirement may not be necessary in small-scale resource lookup.

// Below is an example of how a compliance evaluation table could look. This is presently optional
// and may be moved to a more structured/principled format later maintained in separate files.
[cols="2,1,4,1"]
|====
|Product|Compliant|Justification|Status

| Alvis
| unknown
| ...
| draft

| ARGO/U-Compare
| Components developed for Argo can make use of UIMA's external resources feature, however I don't believe there are many (if any) Argo components that do.  On the Argo development roadmap, we plan on using this approach with Argo reader and writer components.  Currently for every serialisation format (e.g. CAS XMI, RDF/XML) and storage platform (e.g. Argo File Store, SFTP) combination we require a new component to be created.  Instead, we plan to allow the addition of serialisation formats and storage platforms independently.
| draft

| DKPro Core
| partial
| We experimented with such an approach e.g. in the SemanticFieldAnnotator where a resource abstract for semantic tagging resources exists. The idea was e.g. to read semantic tags either from a plain text file or alternatively from a Uby database. The ResourceObjectProvider abstraction internally used by DKPro Core to resolve and load models is also kind of related to this requirement. E.g. there is an experimental function to enable a behind-the-scene sharing of loaded models between multiple component resources. This works provided the models themselves are thread-safe.
| draft

| GATE
| unknown
| ...
| draft

| ILSP
| partial
| Some of the classes that provide access to resource data for ILSP components implement the org.apache.uima.resource.SharedResourceObject interface. 
| draft
|====
