== Output resources of web services/workflows must be accompanied by provenance metadata

[%hardbreaks]
[small]#*_Concreteness:_* __abstract__#
[small]#*_Strength:_* __mandatory__#
[small]#*_Category:_* __WG1__,__WG4__#
[small]#*_Status:_* __deprecated__#

IMPORTANT: This requirement is deprecated. It should be added back as a functional requirement for the workflow execution service (WFEX).

Output resources of web services/workflows must automatically be accompanied by appropriate metadata that can be derived from the usage of the service/workflow (e.g. format, language etc.) & indicating the processing thereof (provenance). 

NOTE: The mechanism of adding this information is a function of the OMTD platform, but the actual values of the elements that need to be enriched or added are dependent on the s/w, so this information must be present in the s/w metadata that describes the output

.See also
* <<REQ-22>>

[cols="2,1,1,4,1"]
|====
|Product|Version|Compliant|Justification|Status

| Alvis
| 0.5rc
| Partial
| Alvis can provide some information, for example data formats and logs
| Final

| ARGO
| 0.5
| No
| Not supported
| Final

| DKPro Core
| 1.8.0
| Partial
| Some information is recoded in the TagSetDescription, TagDescription and DocumentMetaData. 
| Final

| GATE
| 8.2
| No
| Not supported
| Final

| ILSP
| 1.2.1
| Partial
| Only for components integrated in infrastructures like CLARIN and METASHARE. For example https://goo.gl/yDynbu
| Final

|====
