=== Data Category Linking Vocabulary

[%hardbreaks]
[small]#*_Concreteness:_* __abstract__#
[small]#*_Strength:_* __recommended__#
[small]#*_Category:_* __WG2__#
[small]#*_Status:_* __final-phase1__#

Linking elements from different schemas can be modelled in various ways. The most straightforward is the set of coarse grained lightweight thesaural mapping relations expressed by SKOS (https://www.w3.org/2004/02/skos/). This is our preferred linking approach, in combination with the following Owl and RDF object properties:  owl:sameAs, rdfs:subClassOf, and rdfs:subPropertyOf, owl:equivalentClass, and owl:equivalentProperty.
The compliance assessment checks the use of mentioned linking vocabulariess within the KRs themselves, requesting an answer to the question: does the resource contain any of these links?

[cols="2,1,1,4,1"]
|====
|Product|Version|Compliant|Justification|Status

| TheSoz
| June 2016
| Yes
| 
| Final

| Agrovoc
| 21/01/2016
| Yes
| 
| Final

| JATS
| 1.1
| No
| 
| Final

| OLiA
| June 2016
| Yes
| 
| Final

| LAPPS
| June 2016
| Yes
| 
| Final


| Ontolex
| June 2016
| Full
| Documentation is versioned in parallel with the source code
| Final

| CLARIN CCR
| June 2016
| No
| 
| Final

| schema.org
| June 2016
| Yes
| 
| Final

|====