== Components must have a fully qualified name that follows the Java class naming conventions

[%hardbreaks]
[small]#*_Concreteness:_* __concrete__#
[small]#*_Strength:_* __mandatory__#
[small]#*_Category:_* __WG4__#
[small]#*_Status:_* __final__#

Using such a widely adopted naming convention assists component developers through familiarity and helps avoid naming collisions due to the use of use domain names, under the control of the developers, as part of the identifier. It is also the recommended method of identifying components in existing text mining systems such as Argo and GATE. 

NOTE: This requirement was previously titled "Components should be uniquely identified using a string that follows the Java fully-qualified class naming convention". In particular the word "uniquely" has been removed because a Java fully-qualified name does not include version information and in principle there is no safe-guard against having multiple Java classes by the same name on the classpath at the same time. The main point here is that users name their components within a namespace that can be considered under their control. The Java conventions then provide a best-practice how to choose and structure such a namespace. Additional best-practices and techniquees, e.g. the Maven best-practices and version-resolving techniques then should ensure that only a single version of a given component is available at runtime. If a system needs to use multiple versions of a component, additional precautions may need to be necessary.

.See also
* <<REQ-6>>

[cols="2,1,1,4,1"]
|====
|Product|Version|Compliant|Justification|Status

| Alvis
| 0.5rc
| Full
| Components are Java classes organised using packages.
| Draft

| ARGO
| 0.5
| Partial
| All of our current components are identified by strings that follow the Java fully-qualified class naming convention, however as the component identifier within Argo is derived from a filepath it is entirely possible for this requirement to be broken by new components.  For example, the UIMA descriptor for the Argo component Chemical Entity Recogniser has the path `/desc/uk/ac/nactem/uima/ChemicalEntityRecogniser.xml` which translates into the identifier `uk.ac.nactem.uima.ChemicalEntityRecogniser`.
| Draft

| DKPro Core
| 1.8.0
| Full
| Components are identified by a Java class name. Per Java/Maven conventions, this classname is unique within DKPro Core. There is also a version associated with each class corresponding to the version of the enclosing Maven project/JAR.
| Draft

| GATE
| 8.2
| Full
| All GATE components are implemented as Java Beans and as such fulfill this requirement.
| Draft

| ILSP
| 1.2.1
| Full
| Components are identified by a Java class name. They are by convention unique within nlp.ilsp.gr. 
| Draft
|====
