== Attaching format properties to the description of the inputs and outputs that use file

[%hardbreaks]
[small]#*_Concreteness:_* __concrete__#
[small]#*_Strength:_*     __recommended__#
[small]#*_Category:_*     __WG1__,__WG4__#
[small]#*_Status:_*       __draft__#

.See also 
* <<REQ-45>>
* <<REQ-72>>

Some components (tools) will produce and consume files. To reduce mismatches and helps to properly handle the files, the following properties/features about the `file formats` are relevant (to attach to the description of the inputs/outputs that use `file`) :

|===
|Feature | Strength | Description

|id | required | identify the format

|label | optional | label or name to display

|mimeType | optional | mimeType as described in the metadata (e.g., ms:mimeType).

|encoding | optional | identify the character encoding as described in the metadata (e.g., ms:characterEncoding)

|parents | optional | formats from which this format is derived from, that allows to maintain an hierarchie of the formats. (Galaxy administrators do manage datatypes based on a hierarchy of formats)

|doc_url | optional | link to the complete documentation provided in metadata (e.g., ms:documentationURL)
|===

The features are normally present in the metadata (e.g., ms:dataFormat) and in the embedded annotations (e.g., java annotations). To simplify, we can suppose that `id` is the only required element, even if all may be important for the users (e.g., to identify a specific file), the developers (e.g., to understand a file for implementation) or tools (e.g., to automatically process a file).
