== Version documentation in parallel with component/resource

[%hardbreaks]
[small]#*_Concreteness:_* __concrete__#
[small]#*_Strength:_*     __recommended__#
[small]#*_Category:_*     __WG1__,__WG2__,__WG3__,__WG4__#
[small]#*_Status:_*       __draft__#

.See also 
* <<REQ-50>>

To keep the source material (i.e. component/resource) and documentation in sync, it is a good practice to version
documentation along with the source material with identical versions. This means that documentation should reside in a
subdirectory inside the source directory. It is also recommended that the source directory is stored under a
version control repository. Every time a release is made, contents of the release should be identical to a specific
time-state of the repository. This guarantees that each release of the source material contains its corresponding
 documentation and they are always kept in sync.

For software (i.e. components) the documentation should be stored in a module dedicated for this purpose (e.g. for
softwareX there could be softwareX-documentation module).

In some cases a certain version of documentation needs to be updated; for instance, to fix errors or provide more
examples (not typical for software). In this scenario, it is recommended to publish the updated documentation with the
same version identifier but with an updated revision number. For example, if the first documentation is released with
version *v2.0 rev.1* then the updated documentation should be published with version *v2.0 rev.2*. As an alternative,
update date of the document can be attached instead of the revision identifier.

[cols="2,1,1,4,1"]
|====
|Product|Version|Compliant|Justification|Status

| TheSoz
Identifying the version of the associated documentation is optimal, but it still could be linked either to "any later version"| Jun-16
| No
| Documentation is not versioned (http://lod.gesis.org/thesoz/de/help.html)
| Final

| Agrovoc
| 21/01/2016
| No
|
| final

| OLiA
| Jun-16
| No
| No documentation
| Final

| LAPPS
| Jun-16
| No
| The link:http://vocab.lappsgrid.org[LAPPS Web Service Exchange Vocabulary] resides in a version control system, but it does not have a release cycle, unlike the Groovy-based API. Rather, the vocabulary is updated and extended without explicit versioning. It is not clear which verison of the API is compatible with which state of the vocabulary.
| Final

| Licences
| Jun-16
| Unknown
| Version may be provided, yet documentation may use reference to "any later version" (see also <<REQ-50>>)
| Final

| Alvis
| 0.5rc
| No
| No version
| Final

| ARGO
| 0.5
| No
| No versioning of the documentation is performed or enforced by Argo, however this is something that could be adopted.
| Draft

| DKPro Core
| 1.8.0
| Full
| Documentation is versioned in parallel with the source code
| Final

| GATE
| 8.2
| No
| Possible for all GATE components to be written this way although we don't currently enforce it in any way
| Final

| ILSP
| 1.2.1
| No
| No version
| Draft

|====
